# Application configuration
spring.application.name=expense-tracker

# Active Spring Profile (Set to 'postgres' to switch to PostgreSQL)
spring.profiles.active=h2

# Server Port
server.port=8080

# JWT Configuration Properties
# Secret key must be a base64-encoded string of at least 256 bits (32 bytes).
# Below is a 512-bit HS512 secret key base64-encoded
app.jwt.secret=MTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5MA==
# Token validity: 24 hours (in milliseconds)
app.jwt.expiration-ms=86400000
